apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test-component--oiqr
  namespace: build-templates-e2e
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-app-ddhk
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test-component--oiqr
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test-component--oiqr-
      labels:
        build.appstudio.openshift.io/application: test-app-ddhk
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test-component--oiqr
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: build-templates-e2e
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-python-basic
      - name: output-image
        value: quay.io/redhat-appstudio/test-images:c8254209a3f343d48cbce840149fdb4e-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/pull-request-builds:base-d077dc68c84657345efdf703a1f9655aafe3d37c
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: test-component--oiqr/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
